name: express_cart
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core:
    path: core
  data:
    path: data
  domain:
    path: domain

  firebase_module:
    path: 3rd_party/firebase_module
  appwrite_module:
    path: 3rd_party/appwrite_module
  
  get_it: ^7.6.4
  injectable: ^2.3.2
  intl: ^0.19.0
  # agora_rtc_engine: ^6.2.6
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  firebase_auth: ^4.17.1
  formz: ^0.7.0
  flutter_inappwebview: ^6.0.0
  lottie: ^3.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  injectable_generator:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_lints: ^2.0.0
#  flutter_gen_runner: ^5.4.0
  intl_utils: ^2.8.7

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/animations/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MaisonNeue
      fonts:
        - asset: assets/fonts/maison_neue/MaisonNeue-Bold.ttf
          weight: 600
        - asset: assets/fonts/maison_neue/MaisonNeue-Medium.ttf
          weight: 500
        - asset: assets/fonts/maison_neue/MaisonNeue-Book.ttf
          weight: 400
        - asset: assets/fonts/maison_neue/MaisonNeue-Light.ttf
          weight: 200
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
